import { Ionicons } from '@expo/vector-icons';
import { Pressable, Switch, Text, View } from 'react-native';
import { useBudget } from '../context/BudgetContext';
import { colors } from '../constants/theme';
import { Card, Header, SectionTitle, Amount, Screen, styles } from '../components/ui';

export default function BillsScreen() {
  const { bills, toggleBill } = useBudget();
  const activeTotal = bills.filter((bill) => bill.active).reduce((sum, bill) => sum + bill.amount, 0);
  return <Screen><Header title="Bills" subtitle={`${bills.length} recurring payments`} /><Card style={{ marginBottom: 21, backgroundColor: colors.cardSoft }}><Text style={{ color: colors.muted, fontSize: 12, fontWeight: '700' }}>ACTIVE THIS MONTH</Text><Text style={{ color: colors.white, fontSize: 28, fontWeight: '900', marginTop: 7 }}>${activeTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text><Text style={{ color: colors.teal, fontSize: 12, marginTop: 5 }}>Recurring commitments</Text></Card><SectionTitle title="Your recurring bills" action="Edit" />{bills.map((bill) => <Card key={bill.id} style={{ marginBottom: 12, opacity: bill.active ? 1 : 0.55 }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><View style={{ width: 42, height: 42, borderRadius: 14, backgroundColor: `${colors.teal}18`, alignItems: 'center', justifyContent: 'center' }}><Ionicons name="calendar-outline" size={20} color={colors.teal} /></View><View style={{ flex: 1, marginLeft: 12 }}><Text style={{ color: colors.white, fontSize: 15, fontWeight: '800' }}>{bill.merchant}</Text><Text style={styles.subtitle}>{bill.category} · {bill.frequency} · Due {bill.due}</Text></View><Amount value={bill.amount} /></View><View style={{ borderTopWidth: 1, borderTopColor: colors.border, marginTop: 15, paddingTop: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={{ color: colors.muted, fontSize: 12 }}>{bill.active ? 'Included in your plan' : 'Paused'}</Text><Switch value={bill.active} onValueChange={() => toggleBill(bill.id)} trackColor={{ false: colors.border, true: colors.tealDark }} thumbColor={bill.active ? colors.teal : colors.subtle} /></View></Card>)}</Screen>;
}
